# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('filetype', models.CharField(blank=True, max_length=255, null=True, verbose_name='File type')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Report type',
                'verbose_name_plural': 'Report types',
            },
        ),
    ]
