# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('vat', models.CharField(blank=True, max_length=15, null=True, verbose_name='VAT')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address')),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Website')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created')),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Updated')),
                ('is_visible', models.BooleanField(verbose_name='Is Visible')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
