# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('vat', models.CharField(max_length=15, verbose_name='VAT')),
                ('street', models.CharField(max_length=255, verbose_name='Street Address')),
                ('postal_code', models.CharField(max_length=15, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('mobile', models.CharField(max_length=50, verbose_name='Mobile')),
                ('website', models.CharField(max_length=50, verbose_name='Website')),
                ('is_visible', models.BooleanField(verbose_name='Is Visible')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
