# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('price', models.IntegerField(max_length=5, verbose_name='Price')),
                ('is_visible', models.BooleanField(verbose_name='Is Visible')),
                ('parenttask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.TTask')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
