# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Price')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created')),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Updated')),
                ('is_visible', models.BooleanField(verbose_name='Is Visible')),
                ('parenttask', models.ForeignKey(blank=True, db_column='Parent task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.Task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
