# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttask',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
