# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20170713_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttask',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='ttask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ttask',
            name='parenttask',
            field=models.ForeignKey(blank=True, db_column='Parent task', null=True, on_delete=django.db.models.deletion.CASCADE, to='task.TTask'),
        ),
        migrations.AlterField(
            model_name='ttask',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
    ]
