# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20170720_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttask',
            name='parenttask',
            field=models.ForeignKey(blank=True, db_column='Parent task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.TTask'),
        ),
    ]
