# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created')),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Updated')),
                ('is_visible', models.BooleanField(verbose_name='Is Visible')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
