# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproject',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='tproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
