# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='tuser',
            name='description',
            field=models.CharField(max_length=250, verbose_name='description'),
        ),
    ]
