# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170713_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='user',
            field=models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
