# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170713_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
