# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170720_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
