# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('task', '0003_auto_20170713_1143'),
        ('account', '0003_auto_20170713_1144'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('starttime', models.DateTimeField(verbose_name='Start date / time')),
                ('endtime', models.DateTimeField(verbose_name='End date / time')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('client', models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.CASCADE, to='client.TClient')),
                ('project', models.ForeignKey(db_column='Project', on_delete=django.db.models.deletion.CASCADE, to='project.TProject')),
                ('task', models.ForeignKey(db_column='Task', on_delete=django.db.models.deletion.CASCADE, to='task.TTask')),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to='account.TUser')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
