# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 17:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('client', '0001_initial'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('starttime', models.CharField(max_length=20, verbose_name='Start date / time')),
                ('endtime', models.CharField(max_length=20, verbose_name='End date / time')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('client', models.ForeignKey(blank=True, db_column='Client', null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to='client.Client')),
                ('project', models.ForeignKey(blank=True, db_column='Project', null=True,
                                              on_delete=django.db.models.deletion.SET_NULL, to='project.Project')),
                ('task', models.ForeignKey(blank=True, db_column='Task', null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, to='task.Task')),
                ('user', models.ForeignKey(blank=True, db_column='User', null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
