# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20170801_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='endtime',
            field=models.CharField(max_length=20, verbose_name='End date / time'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='starttime',
            field=models.CharField(max_length=20, verbose_name='Start date / time'),
        ),
    ]
